### PR TITLE
Admin Manage Comment

### PR DESCRIPTION
**Pull request by Baotranviet**

### CODE REVIEW

**Comment by Baotranviet** [comment]
ready

**Comment by Baotranviet** [comment]
ready

**Comment by Baotranviet** [comment]
ready

**Comment by Baotranviet** [comment]
open

**Comment by Baotranviet** [comment]
ready

**Comment by Baotranviet** [comment]
ready

**Comment by quoctd-0607** [comment]
commented
conflict code

**Comment by Baotranviet** [comment]
ready

**Pull request merged**
